### ISSUE TITLE
very bad app

### ISSUE THREAD

**Issue by geogesif** [RomascuAndrei/BTNotifierAndroid#1]
All time close

**Comment by geogesif** [comment]
....


O:-)

**Comment by nathymg94** [comment]
Who are u??



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: geogesif <notifications@github.com>
Fecha: 17/9/18 14:53 (GMT-05:00)
A: RomascuAndrei/BTNotifierAndroid <BTNotifierAndroid@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [RomascuAndrei/BTNotifierAndroid] very bad app (#1)


Closed #1<https://github.com/RomascuAndrei/BTNotifierAndroid/issues/1>.
